### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by epoyraz** [manuels/texlive.js#10]
I would like to use texlive.js in a commercial web-app.

Am i allowed to use it ?

**Comment by swayf** [comment]
in this case LGPL should be fine? because in case of GPL you have to open all you sources, not only changes in textlive.js

**Comment by davelab6** [comment]
No, the LGPL can't be used because it inherits the GPL from pdflatex

**Comment by TheodoreChu** [comment]
Would you consider updating the license to "GPL-2 **or any later version**" so that it's compatible with GPL-3 and AGPL-3?

**Comment by theodorechu** [comment]
Would you consider updating the license to "GPL-2 **or any later version**" so that it's compatible with GPL-3?
