### ISSUE TITLE
XeLaTeX

### ISSUE THREAD

**Issue by hoorzad** [manuels/texlive.js#4]
Is it possible that you make a js version of xelatex as well? I work with bidirectional documents that can't be compiled properly with pdftex.

**Comment by lyze** [comment]
I'm a little late to the party, but here's `xelatex` and `xdvipdfmx` in Javascript: [lyze/xetex-js](https://github.com/lyze/xetex-js).

**Comment by manuels** [comment]
Cool, nice project, @lyze!
