### ISSUE TITLE
adding a style while compiling

### ISSUE THREAD

**Issue by s6fikass** [manuels/texlive.js#45]
In texlive the Unix version it is possible to add a cls file which contain a certain style to the tex document and the result is the pdf with styles represented 
Does texlive .js provide the same function

**Comment by manuels** [comment]
Sure, you can create new files in the virtual filesystem which points to a URL.
See https://github.com/manuels/texlive.js/blob/gh-pages/index.html#L180 and https://github.com/manuels/texlive.js/blob/gh-pages/pdftex.js#L117

**Comment by s6fikass** [comment]
But will the result pdf have the style present in the .cls
i am trying to apply what is mentioned [here](http://www.springer.com/computer/lncs/lncs+authors?SGWID=0-40209-0-0-0)

**Comment by manuels** [comment]
sure, if you specify in your .tex file that this .cls should be used.
