### ISSUE TITLE
Help for a beginner?

### ISSUE THREAD

**Issue by makinavava1978** [manuels/texlive.js#46]
Hello everyone,

I'm creating a web where I would like to generate pdf files from latex format, and I thought that texlive.js would be useful for this purpose but I'm not able to make it work. 

At the moment, I have  only been able to download the files on my computer and run the index.html (like http://manuels.github.io/texlive.js) with Mozilla (when I use Chrome it doesn't work). However, when I copy the files and folders (with the same structure) to my server I can load the main page (index.html) but once I push the "Compile this LaTeX code to a PDF" button, in the "console output"  appears the message "Compiling", but keeping in this state for the eternity.

Any ideas about what I could be doing wrong? Some suggestions for the beginners would be welcome ;) Thanks,

Maki.
PD: Sorry for my English mistakes, but I'm from Spain and my language skills aren't the best ones.

**Comment by manuels** [comment]
Hey, do you have a link to this website?

**Comment by makinavava1978** [comment]
Hey,
The link of my website? It is the following,
http://www.mates123.com

**Comment by manuels** [comment]
Well, I get the error

    GET http://www.mates123.com/promisejs/promise.js [HTTP/1.1 404 Not Found 26ms]

**Comment by makinavava1978** [comment]
Should I copy the files from this link 
https://github.com/stackp/promisejs/tree/2ac90b7c04cf3095d58659649b98d66a3e5ad2f2
in the empty folder?

**Comment by manuels** [comment]
yep

**Comment by makinavava1978** [comment]
Hey,
Thank four your instant answer, but I did it and I still have the same problem...

**Comment by manuels** [comment]
Check out [the network monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor): `http://www.mates123.com/texlive.lst` is missing

**Comment by makinavava1978** [comment]
Hey,

Thanks for your help. I copied the file http://manuels.github.io/texlive.js/texlive.lst in my website but when I tried to see it in http://www.mates123.com/texlive.lst it is missing. I will read carefully the link you told me (https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor) because the first attempt it was to hard for me... 

Thank you again Manuels, I will tell you if I do some progress.

Maki

**Comment by makinavava1978** [comment]
Hi again,

For any unknown reason I cannot see the file  http://www.mates123.com/texlive.lst from the browser, but when I check it using FileZilla the file is there. Any idea how can I solve it? Here the image I capture in FileZilla, texlive.lst appears like a Excel document because I asociated LST with this program, but it is the one I download from  http://manuels.github.io/texlive.js/texlive.lst.
![image_texlive_lst](https://cloud.githubusercontent.com/assets/22427450/18816210/1044ee34-8345-11e6-9f48-d47d8f19eb2a.png)

**Comment by makinavava1978** [comment]
Hi,

I have checked that if I change the extension of the file, then it is visible: http://www.mates123.com/texlive.txt
I don't know if this adds some relevant information...

Maki

**Comment by makinavava1978** [comment]
Hi,

I could solve the problem and now it is working. I had to add some lines in the file "web.config" to permit my server works with some non-habitual extensions.

The lines I add after the line "< system.webServer  >" are:

        <staticContent>
         <mimeMap fileExtension=".lst" mimeType="application/octet-stream" />
         <mimeMap fileExtension="." mimeType="application/octet-stream" />
		 <mimeMap fileExtension=".fmt" mimeType="application/octet-stream" />
		 <mimeMap fileExtension=".cls" mimeType="application/octet-stream" />
		 <mimeMap fileExtension=".clo" mimeType="application/octet-stream" />
		 <mimeMap fileExtension=".tfm" mimeType="application/x-tex-tfm" />
		 <mimeMap fileExtension=".sty" mimeType="application/octet-stream" />
		 <mimeMap fileExtension=".cfg" mimeType="application/octet-stream" />
		 <mimeMap fileExtension=".def" mimeType="text/plain" />
		 <mimeMap fileExtension=".mkii" mimeType="application/octet-stream" />
      </staticContent>

Thanks Manuel for the first clues. Bye,

Maki.

**Comment by manuels** [comment]
Great, good to hear!
