### ISSUE TITLE
Build fails due to non-existent directories in pdftex

### ISSUE THREAD

**Issue by TilBlechschmidt** [manuels/texlive.js#51]
I attempted to build texlive.js by starting up [this docker container](https://hub.docker.com/r/apiaryio/emcc/), then executing these commands inside the git repo
```
apt-get update
apt-get install git llvm default-jre wget unzip texinfo texlive-latex-base texlive-fonts-recommended texlive-fonts-extra

git submodule init
git submodule update

make
```
ultimately running into this error
![img-2017-04-29-103603](https://cloud.githubusercontent.com/assets/5037967/25554218/03077318-2cc8-11e7-9e27-32bb61389418.png)
Executing this command
```
mkdir -p ./binary/pdftex-1.40.11/build-pdftex/texk/web2c/pdftex
```
gets me past the first error eventually (only when executed in a specific order like `make clean && mkdir ... && make`) but the second one still makes it fail.

I somehow got it to installing all texlive packages but then again same story. The very same directory disappeared and the pdftex worker does not get built.
![img-2017-04-29-104912](https://cloud.githubusercontent.com/assets/5037967/25554287/a5043466-2cc9-11e7-8820-a5f3cf97e608.png)

I'm running emscripten 1.37.10.

**Comment by TilBlechschmidt** [comment]
nvmd it was due to g++ and gcc not being present in the container. I though it was part of the build-essentials package group but apparently I was mistaken :smile:

**Comment by manu189** [comment]
Hallo  @TilBlechschmidt I'm new to js and I'm trying to use texlive.js for a project. I'm getting the exact same error. What I did was just git clone the repository and then make. I tried apt-get install gcc but it didn't work. Could you elaborate on the solution a little bit, thank you!
