### ISSUE TITLE
Is xeLaTeX supported?

### ISSUE THREAD

**Issue by SamuelCui** [manuels/texlive.js#55]
I understand several years ago this question had been asked, and Manuels said maybe they would make a xeLaTeX js in the future. Can I ask when will we have it? I am really in a desperate need of xeLaTeX.

**Comment by manuels** [comment]
Sorry, I don't think that will happen. I won't have time to port it.

**Comment by SamuelCui** [comment]
Thank you for letting me know. Thank you for the wonderful TexLive.
