### ISSUE TITLE
shared:ERROR: closure compiler failed (rc: 1)

### ISSUE THREAD

**Issue by poush** [manuels/texlive.js#58]
Every time I try to compile, closure compiler throws an error:

`/tmp/emscripten_temp_vx7x3kzq/pdftex-worker.bc.o.js.pp.js.mem.js.jso.js.jso.js.jso.js.jso.js:1: ERROR - Variable Module declared more than once. First occurrence: /tmp/emscripten_temp_vx7x3kzq/pdftex-worker.bc.o.js.pp.js.mem.js.jso.js.jso.js.jso.js.jso.js`

Any possible solution to this?

**Comment by poush** [comment]
Fixed.

**Comment by seuliang** [comment]
I have the same problem!
Could you tell me how to fix this?

**Comment by seuliang** [comment]
> Fixed.

@poush @manuels 
I have the same problem!
Could you tell me how to fix this?

**Comment by fzimmermann89** [comment]
I will have take a look at this project again next week.

In the meantime:there is probably an issue with glue code that calls the compiled texlive (somewhere in the pre and post js files)
You can also just disable the closure optimisation in the Makefile by removing all mentions of --closure 1
More info at
https://emscripten.org/docs/optimizing/Optimizing-Code.html under closure compilation.

**Comment by seuliang** [comment]
confirm that remove `--closure 1` can finish compile.
However, when compiling latex file to pdf, console output stops at 
Compiling…  
Because no file in ./promisejs after compile.
