### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by MariusHerget** [manuels/texlive.js#61]
The implementation is really nice but performance wise it's just bad. Loading all package files synchronous takes about  100ms per file which adds up quite fast. My local compiling takes about 4 seconds. Texlive.js takes 80 seconds.

Is there any solution to preloading necessary files or loading all files asynchronously? 

In my usecase I know 100% of the packages pre compiling of the tex file.

Maybe @manuels or @fzimmermann89 ?

**Comment by manuels** [comment]
Sure, you could use the `FS_createDataFile` command (see `pdftex.js`)

**Comment by MariusHerget** [comment]
@manuels do you have a specific installation guide? Unfortunately, the documentation of pdftex.js (ctan) is down. 

btw: great work on texlive.js!
